name: upload
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: zcong1993/setup-timezone@master
        with:
          timezone: America/Chicago
      - run: npm install
      - run: npm run start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
